### Get all professions
GET http://localhost:8080/api/professions
Accept: application/json

### Get a profession by ID
GET http://localhost:8080/api/professions/c18b235d-d038-440c-b37d-7ff782e4f692
Accept: application/json

### Get all characters
GET http://localhost:8080/api/characters
Accept: application/json

### Get a user by ID
GET http://localhost:8080/api/characters/c5a61254-6e4a-4c73-98c0-2dd8daa45c10
Accept: application/json

### Create a new user
PUT http://localhost:8080/api/characters/c5a61254-6e4a-4c73-98c0-2dd8daa45c90
Content-Type: application/json

{
    "name": "dss",
    "level": 12,
    "professionId": "66582c41-ad42-45f0-a5c6-eab3aa78e00f"
}

### Delete a user
# Replace {{userIdToDelete}} with the ID of the user you want to delete.
DELETE http://localhost:8080/api/characters/c5a61254-6e4a-4c73-98c0-2dd8daa45c90
